# Generated by Django 4.2.5 on 2023-09-15 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('album_name', models.CharField(db_column='album', max_length=300)),
                ('artist_name', models.CharField(db_column='artist_name', max_length=300)),
                ('genre', models.CharField(max_length=100)),
                ('year', models.SmallIntegerField()),
                ('length', models.IntegerField()),
                ('bitrate', models.IntegerField()),
                ('lyrics', models.TextField(null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='music_api.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='music_api.artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='music_api.artist'),
        ),
    ]
