name: Django Music API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.3"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up git-crypt
      run: |
        echo ${{ secrets.GIT_CRYPT_KEY }}" > .git-crypt/keyfile
        git-crypt unlock .git-crypt/keyfile
      env:
        GIT_CRYPT_KEY_PATH: .git-crypt/keyfile

    - name: Decrypt .env file
      run: |
        git-crypt unlock "$GIT_CRYPT_KEY_PATH"
      env:
        GIT_CRYPT_KEY_PATH: .git-crypt/keyfile
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install
        
    - name: Run Tests
      run: |
        pipenv run python manage.py test
